version: '3.4'

services:
  webapp:
    build: .
    image: ghcr.io/markhuang1212/aka
    ports:
      - 8080:8080
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - APP_DATA=/data
    volumes:
      - .:/data
  cloudflared:
    image: cloudflare/cloudflared:2021.11.0
    volumes:
      - ~/.cloudflared:/etc/cloudflared
    command: tunnel --hostname hmpg.dev --url http://webapp:8080
    
