version: '3.4'

services:
  webapp:
    build: .
    image: ghcr.io/markhuang1212/aka
    ports:
      - 8080:8080
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - APP_DATA=/data
    volumes:
      - .:/data